export type Language = 'hindi' | 'english';
export type GSTRate = 0 | 5 | 9 | 12 | 18;
export type LetterheadFitMode = 'contain' | 'cover' | 'stretch';
export type FirmStyleProfile = 'govt_formal' | 'minimal_business' | 'bilingual' | 'table_heavy';
export type TenderStatus = 'draft' | 'final';
export type TenderDocType =
  | 'vigyapti'
  | 'quotation_main'
  | 'quotation_alt_1'
  | 'quotation_alt_2'
  | 'supply_aadesh'
  | 'firm_bill';

export interface BaseEntity {
  id: string;
  createdAt: string;
  updatedAt: string;
}

export interface TenderItem extends BaseEntity {
  tenderId: string;
  productName: string;
  description?: string;
  category?: string;
  quantity: number;
  unit?: string;
  rate: number;
  gstPercent: GSTRate;
  estimatedAmount?: number;
  totalAmount: number;
}

export interface PurposeMapping extends BaseEntity {
  category: string;
  professionalPurpose: string;
  language: Language;
  usageCount: number;
  isAutoGenerated: boolean;
}

export interface HindiMapping extends BaseEntity {
  rawName?: string;
  rawDescription?: string;
  englishName: string;
  hindiName: string;
  englishDescription?: string;
  hindiDescription?: string;
  altHindiName?: string;
  altHindiName2?: string;
  altEnglishName1?: string;
  altEnglishName2?: string;
  type: 'item' | 'vendor';
  usageCount: number;
  isAutoGenerated: boolean;
}

// ─── Document Phrase Mappings ──────────────────────────────────────────────

export interface DocumentPhrases {
  supplyOrder: {
    subject: string;
  };
  quotationMain: {
    english: string;  // e.g. "To give the Quotations of Dustbin."
    hindi: string;    // Hindi transliteration of the English line
  };
  quotation: {
    purchaseLine: string;
  };
  quotationAltHindi: {
    subject: string;
  };
  quotationAltEnglish: {
    subject: string;
  };
  bill: {
    itemDescription: string;
  };
}

export interface DocumentPhraseMapping extends BaseEntity {
  categoryName: string;  // display e.g. "Dustbin"
  categoryId: string;    // slug  e.g. "dustbin"
  keywords: string[];    // ["dustbin","waste bin","pedal bin",…]
  phrases: DocumentPhrases;
  generatedByAI: boolean;
  approved: boolean;
  usageCount: number;
  lastUsedAt?: string;
  englishDescription?: string;
}

export interface PlaceMapping extends BaseEntity {
  englishName: string;
  hindiName: string;
  districtName: string;
  districtHindiName?: string;
  stateName: string;
  stateHindiName?: string;
  localBodyType?: string;
  localBodyTypeHindi?: string;
  usageCount: number;
  isAutoGenerated: boolean;
}

export interface LocalBodyType extends BaseEntity {
  englishName: string;
  hindiName: string;
  usageCount: number;
  isDefault: boolean;
}

export interface AILocationCache extends BaseEntity {
  query: string;
  englishName: string;
  hindiName?: string;
  districtName: string;
  districtHindiName?: string;
  stateName: string;
  stateHindiName?: string;
  confidence: number;
  provider: string;
}

export interface DepartmentProfile extends BaseEntity {
  name: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  contactPerson: string;
  email: string;
  phone: string;
  headerStyle: 'standard' | 'govt' | 'custom';
  defaultLanguage: Language;
}

export interface Tender extends BaseEntity {
  title: string;
  tenderNumber: string;
  departmentProfileId: string;
  mainFirmId: string;
  alternateFirms?: string[];
  items: TenderItem[];
  language: Language;
  status: TenderStatus;
  description?: string;
  notes?: string;
  version: number;
  parentTenderId?: string;
  // New fields for government tender workflow
  tenderType?: string;
  placeName?: string;
  districtName?: string;
  localBodyType?: string;
  localBodyTypeHindi?: string;
  publishDate?: string;
  submissionDate?: string;
  openingDate?: string;
  estimatedBudget?: number;
  estimatedAmount?: number;
}

export interface Firm extends BaseEntity {
  name: string;
  headerImagePath: string;
  signatureImagePath?: string;
  stampImagePath?: string;
  defaultLanguage: Language;
  fitLetterheadMode: LetterheadFitMode;
  /**
   * New simplified layout controls (used by preview + PDF layout).
   * Values are px.
   */
  headerSpacing: number;
  footerSpacing: number;
  pageMargin: number;
  /**
   * Width of the A4 preview frame when layout controls were last saved.
   * Used to scale preview-positioned px values into the final A4 renderer.
   */
  layoutReferenceWidth?: number;

  /**
   * Legacy layout fields kept for backward compatibility with older stored data.
   * Do not expose in UI.
   */
  contentStartY?: number;
  pagePaddingLeft?: number;

  /**
   * Optional positioning controls (px), measured from the bottom-right corner of the page.
   */
  signatureOffsetX?: number;
  signatureOffsetY?: number;
  signatureScale?: number;
  signatureRotateDeg?: number;
  stampOffsetX?: number;
  stampOffsetY?: number;
  stampScale?: number;
  stampMode?: 'image' | 'generic';
  aiPromptQuotation: string;
  aiPromptBill?: string;
  firmStyleProfile: FirmStyleProfile;
  // New fields for firm details
  firmCity?: string;
  firmAddress?: string;
  gstNumber?: string;
  mobileNumber?: string;
  contactPerson?: string;
  // Vendor Hindi name for firm/vendor transliteration
  vendorHindiName?: string;
  // Bill details for firm bill generation
  bankName?: string;
  bankBranch?: string;
  ifscCode?: string;
  accountNumber?: string;
  panNumber?: string;
  billInstructions?: string;
  customQuotationTemplateId?: string;
  customBillTemplateId?: string;
}

export interface BillItem {
  id: string;
  productName: string;
  description?: string;
  quantity: number;
  unit?: string;
  rate: number;
  amount: number;
}

export interface Bill extends BaseEntity {
  invoiceNumber: string;
  invoiceDate: string;
  firmId: string;
  customTemplateId?: string;
  recipientDesignation: string;
  recipientDepartment: string;
  recipientDistrict: string;
  recipientAddress?: string;
  items: BillItem[];
  sgstPercent: number;
  cgstPercent: number;
  igstPercent: number;
  totalAmount: number;
  sgstAmount: number;
  cgstAmount: number;
  igstAmount: number;
  grandTotal: number;
  amountInWords: string;
  status: 'draft' | 'final';
  showLetterheadBackground?: boolean;
  includeSignature?: boolean;
  includeStamp?: boolean;
  notes?: string;
}

export interface DocumentVersion extends BaseEntity {
  documentId: string;
  versionNumber: number;
  contentHTML: string;
  changeNote?: string;
  contentDiff?: string;
  isCompressed?: boolean;
}

export interface TenderDocument extends BaseEntity {
  tenderId: string;
  docType: TenderDocType;
  contentHTML: string;
  pdfPath?: string;
  lastModified?: string;
  currentVersion: number;
  versions: DocumentVersion[];
  showLetterheadBackground: boolean;
  showSafeMarginGuide: boolean;
  lockHeaderPosition: boolean;
  includeSignature: boolean;
  includeStamp: boolean;
  footerNotes?: string;
  overflowWarning?: string;
}

export interface Settings extends BaseEntity {
  organizationName: string;
  departmentAddress: string;
  contactPerson: string;
  email: string;
  phone: string;
  defaultLanguage: Language;
  headerSafeZonePx: number;
  tenderNumberPrefix: string;
  enableLocationAIAutofill: boolean;
  versioningSettings: VersioningSettings;
}

export interface VersioningSettings {
  enabled: boolean;
  maxVersions: number;
  autoSaveEnabled: boolean;
  autoSaveInterval: number;
  changeNotesRequired: boolean;
  versionRetentionDays: number;
  enableVersionComparison: boolean;
}

export interface PriceVariation {
  type: 'main' | 'alt_1' | 'alt_2';
  multiplier: number;
  finalPrice: number;
}

export interface CustomTemplate extends BaseEntity {
  name: string;
  docType: TenderDocType;
  language: Language;
  content: string;
  fontFamily?: string;
}
