import { AILocationCache, LocalBodyType, PlaceMapping } from '@/types';
import { dataService } from '@/services/dataService';

export interface LocationSuggestion {
  place: PlaceMapping;
  score: number;
}

export interface AILocationResult {
  englishName: string;
  hindiName?: string;
  districtName: string;
  districtHindiName?: string;
  stateName: string;
  stateHindiName?: string;
  confidence: number;
  source: 'cache' | 'ai' | 'local';
}

const FALLBACK_LOCAL_BODY_TYPES: LocalBodyType[] = [
  {
    id: 'fallback-nagar-palika-parishad',
    englishName: 'Nagar Palika Parishad',
    hindiName: 'नगर पालिका परिषद',
    usageCount: 0,
    isDefault: true,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'fallback-nagar-parishad',
    englishName: 'Nagar Parishad',
    hindiName: 'नगर परिषद',
    usageCount: 0,
    isDefault: true,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'fallback-nagar-palika',
    englishName: 'Nagar Palika',
    hindiName: 'नगर पालिका',
    usageCount: 0,
    isDefault: true,
    createdAt: '',
    updatedAt: '',
  },
];

function normalizeSearch(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '');
}

function scorePlace(query: string, place: PlaceMapping): number {
  const normalizedQuery = normalizeSearch(query);
  if (!normalizedQuery) return 0;

  const candidates = [
    place.englishName,
    place.hindiName,
    place.districtName,
    place.districtHindiName || '',
    place.stateName,
    place.stateHindiName || '',
  ].map(normalizeSearch);

  if (candidates.some((candidate) => candidate === normalizedQuery)) return 100;
  if (candidates.some((candidate) => candidate.startsWith(normalizedQuery))) return 80;
  if (candidates.some((candidate) => candidate.includes(normalizedQuery))) return 60;

  const compactQuery = normalizedQuery.replace(/\s+/g, '');
  if (candidates.some((candidate) => candidate.replace(/\s+/g, '').includes(compactQuery))) return 45;

  return 0;
}

function cacheToResult(cache: AILocationCache): AILocationResult {
  return {
    englishName: cache.englishName,
    hindiName: cache.hindiName,
    districtName: cache.districtName,
    districtHindiName: cache.districtHindiName,
    stateName: cache.stateName,
    stateHindiName: cache.stateHindiName,
    confidence: cache.confidence,
    source: 'cache',
  };
}

export async function searchPlaces(query: string, maxResults = 8): Promise<LocationSuggestion[]> {
  const places = await dataService.placeMappings.list();
  return places
    .map((place) => ({ place, score: scorePlace(query, place) }))
    .filter((entry) => entry.score > 0)
    .sort((left, right) => right.score - left.score || right.place.usageCount - left.place.usageCount)
    .slice(0, maxResults);
}

export async function createPlaceMapping(
  data: Pick<
    PlaceMapping,
    | 'englishName'
    | 'hindiName'
    | 'districtName'
    | 'districtHindiName'
    | 'stateName'
    | 'stateHindiName'
    | 'localBodyType'
    | 'localBodyTypeHindi'
  >,
  isAutoGenerated = false
): Promise<PlaceMapping> {
  return dataService.placeMappings.create({
    ...data,
    usageCount: 0,
    isAutoGenerated,
  });
}

export async function updatePlaceMapping(
  id: string,
  data: Partial<Pick<
    PlaceMapping,
    | 'englishName'
    | 'hindiName'
    | 'districtName'
    | 'districtHindiName'
    | 'stateName'
    | 'stateHindiName'
    | 'localBodyType'
    | 'localBodyTypeHindi'
  >>
): Promise<PlaceMapping | undefined> {
  return dataService.placeMappings.update(id, data);
}

export async function markPlaceUsed(place: PlaceMapping): Promise<void> {
  await dataService.placeMappings.update(place.id, { usageCount: place.usageCount + 1 });
}

export async function listLocalBodyTypes(): Promise<LocalBodyType[]> {
  const bodyTypes = await dataService.localBodyTypes.list();
  return bodyTypes.length > 0 ? bodyTypes : FALLBACK_LOCAL_BODY_TYPES;
}

export async function createLocalBodyType(
  data: Pick<LocalBodyType, 'englishName' | 'hindiName'>
): Promise<LocalBodyType> {
  return dataService.localBodyTypes.create({
    ...data,
    usageCount: 0,
    isDefault: false,
  });
}

export async function markLocalBodyTypeUsed(bodyType: LocalBodyType): Promise<void> {
  await dataService.localBodyTypes.update(bodyType.id, { usageCount: bodyType.usageCount + 1 });
}

export async function fetchDistrict(placeName: string): Promise<AILocationResult | null> {
  const query = normalizeSearch(placeName);
  if (!query) return null;

  const cached = await dataService.aiLocationCache.get(query);
  if (cached) return cacheToResult(cached);

  const localMatch = (await searchPlaces(placeName, 1))[0];
  if (localMatch && localMatch.score >= 60) {
    return {
      englishName: localMatch.place.englishName,
      hindiName: localMatch.place.hindiName,
      districtName: localMatch.place.districtName,
      districtHindiName: localMatch.place.districtHindiName,
      stateName: localMatch.place.stateName,
      stateHindiName: localMatch.place.stateHindiName,
      confidence: localMatch.score / 100,
      source: 'local',
    };
  }

  try {
    const response = await fetch('/api/ai/location', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ placeName }),
    });
    if (!response.ok) return null;
    const result = (await response.json()) as AILocationResult | null;
    if (!result?.districtName || !result?.englishName) return null;

    await dataService.aiLocationCache.set({
      query,
      englishName: result.englishName,
      hindiName: result.hindiName || '',
      districtName: result.districtName,
      districtHindiName: result.districtHindiName || '',
      stateName: result.stateName || 'Madhya Pradesh',
      stateHindiName: result.stateHindiName || 'मध्य प्रदेश',
      confidence: result.confidence,
      provider: 'location-api',
    });

    return { ...result, source: 'ai' };
  } catch {
    return null;
  }
}

export const locationService = {
  searchPlaces,
  createPlaceMapping,
  updatePlaceMapping,
  markPlaceUsed,
  listLocalBodyTypes,
  createLocalBodyType,
  markLocalBodyTypeUsed,
  fetchDistrict,
};
