import { dataService } from './dataService';
import { transliterate, AIProvider } from './aiClient';
import { HindiMapping } from '@/types';

/**
 * Mapping Service
 * Simplified service for managing procurement purpose mappings and Hindi transliteration.
 * 
 * Key features:
 * - Category-based purpose mappings (not item-based)
 * - AI transliteration API call once for unknown items, then reuse
 * - No complex phonetic engine needed
 */

const TEMPORARY_PURPOSE_HINDI = 'संबंधित कार्य हेतु आवश्यक सामग्री';
const TEMPORARY_PURPOSE_ENGLISH = 'Relevant work materials required';

// Export constants for testing
export { TEMPORARY_PURPOSE_HINDI, TEMPORARY_PURPOSE_ENGLISH };

/**
 * Get professional purpose by category
 * Falls back to temporary purpose if no mapping exists
 */
export async function getPurposeByCategory(category: string, language: 'hindi' | 'english' = 'hindi'): Promise<string> {
  try {
    const mapping = await dataService.purposeMappings.get(category, language);
    if (mapping) {
      // Increment usage count
      await dataService.purposeMappings.update(mapping.id, {
        usageCount: (mapping.usageCount || 0) + 1,
      });
      return mapping.professionalPurpose;
    }
    
    // No mapping found, return temporary purpose
    return language === 'hindi' ? TEMPORARY_PURPOSE_HINDI : TEMPORARY_PURPOSE_ENGLISH;
  } catch (error) {
    console.error('Error getting purpose by category:', error);
    return language === 'hindi' ? TEMPORARY_PURPOSE_HINDI : TEMPORARY_PURPOSE_ENGLISH;
  }
}

/**
 * Set professional purpose by category
 */
export async function setPurposeByCategory(
  category: string,
  purpose: string,
  language: 'hindi' | 'english' = 'hindi'
): Promise<void> {
  try {
    // Check if mapping already exists
    const existing = await dataService.purposeMappings.get(category, language);
    
    if (existing) {
      // Update existing mapping
      await dataService.purposeMappings.update(existing.id, {
        professionalPurpose: purpose,
        isAutoGenerated: false,
      });
    } else {
      // Create new mapping
      await dataService.purposeMappings.create({
        category,
        professionalPurpose: purpose,
        language,
        usageCount: 0,
        isAutoGenerated: false,
      });
    }
  } catch (error) {
    console.error('Error setting purpose by category:', error);
    throw error;
  }
}

/**
 * Get all purpose mappings
 */
export async function getAllPurposeMappings() {
  try {
    return await dataService.purposeMappings.list();
  } catch (error) {
    console.error('Error getting all purpose mappings:', error);
    return [];
  }
}

/**
 * Delete purpose mapping by category (deletes both language versions)
 */
export async function deletePurposeMapping(category: string): Promise<boolean> {
  try {
    // Delete both Hindi and English mappings for this category
    const hindiMapping = await dataService.purposeMappings.get(category, 'hindi');
    const englishMapping = await dataService.purposeMappings.get(category, 'english');
    
    let deleted = false;
    if (hindiMapping) {
      deleted = await dataService.purposeMappings.delete(hindiMapping.id);
    }
    if (englishMapping) {
      deleted = await dataService.purposeMappings.delete(englishMapping.id);
    }
    return deleted;
  } catch (error) {
    console.error('Error deleting purpose mapping:', error);
    return false;
  }
}

/**
 * Get Hindi name for an item
 * Calls AI transliteration API once for unknown items, then reuse
 */
export async function getHindiItemName(itemName: string): Promise<string> {
  try {
    const mapping = await dataService.itemHindiMappings.get(itemName);
    if (mapping) {
      // Increment usage count
      await dataService.itemHindiMappings.update(mapping.id, {
        usageCount: (mapping.usageCount || 0) + 1,
      });
      return mapping.hindiName;
    }
    
    // No mapping found, call AI transliteration API
    const hindiName = await transliterateToHindi(itemName);
    
    // Save the mapping for future use
    await dataService.itemHindiMappings.create({
      englishName: itemName,
      hindiName,
      type: 'item' as const,
      usageCount: 1,
      isAutoGenerated: true,
    });
    
    return hindiName;
  } catch (error) {
    console.error('Error getting Hindi item name:', error);
    return itemName; // Fallback to original name
  }
}

/**
 * Set Hindi name for an item
 */
export async function setHindiItemName(itemName: string, hindiName: string): Promise<void> {
  try {
    // Check if mapping already exists
    const existing = await dataService.itemHindiMappings.get(itemName);
    
    if (existing) {
      // Update existing mapping
      await dataService.itemHindiMappings.update(existing.id, {
        hindiName,
        isAutoGenerated: false,
      });
    } else {
      // Create new mapping
      await dataService.itemHindiMappings.create({
        englishName: itemName,
        hindiName,
        type: 'item' as const,
        usageCount: 0,
        isAutoGenerated: false,
      });
    }
  } catch (error) {
    console.error('Error setting Hindi item name:', error);
    throw error;
  }
}

/**
 * Get Hindi name for a vendor
 * Calls AI transliteration API once for unknown vendors, then reuse
 */
export async function getHindiVendorName(vendorName: string): Promise<string> {
  try {
    const mapping = await dataService.vendorHindiMappings.get(vendorName);
    if (mapping) {
      // Increment usage count
      await dataService.vendorHindiMappings.update(mapping.id, {
        usageCount: (mapping.usageCount || 0) + 1,
      });
      return mapping.hindiName;
    }
    
    // No mapping found, call AI transliteration API
    const hindiName = await transliterateToHindi(vendorName);
    
    // Save the mapping for future use
    await dataService.vendorHindiMappings.create({
      englishName: vendorName,
      hindiName,
      type: 'vendor' as const,
      usageCount: 1,
      isAutoGenerated: true,
    });
    
    return hindiName;
  } catch (error) {
    console.error('Error getting Hindi vendor name:', error);
    return vendorName; // Fallback to original name
  }
}

/**
 * Set Hindi name for a vendor
 */
export async function setHindiVendorName(vendorName: string, hindiName: string): Promise<void> {
  try {
    // Check if mapping already exists
    const existing = await dataService.vendorHindiMappings.get(vendorName);
    
    if (existing) {
      // Update existing mapping
      await dataService.vendorHindiMappings.update(existing.id, {
        hindiName,
        isAutoGenerated: false,
      });
    } else {
      // Create new mapping
      await dataService.vendorHindiMappings.create({
        englishName: vendorName,
        hindiName,
        type: 'vendor' as const,
        usageCount: 0,
        isAutoGenerated: false,
      });
    }
  } catch (error) {
    console.error('Error setting Hindi vendor name:', error);
    throw error;
  }
}

/**
 * Get all item Hindi mappings
 */
export async function getAllItemHindiMappings() {
  try {
    return await dataService.itemHindiMappings.list();
  } catch (error) {
    console.error('Error getting all item Hindi mappings:', error);
    return [];
  }
}

/**
 * Get all vendor Hindi mappings
 */
export async function getAllVendorHindiMappings() {
  try {
    return await dataService.vendorHindiMappings.list();
  } catch (error) {
    console.error('Error getting all vendor Hindi mappings:', error);
    return [];
  }
}

/**
 * Transliterate English text to Hindi using AI API
 */
async function transliterateToHindi(text: string): Promise<string> {
  try {
    const provider = (process.env.NEXT_PUBLIC_AI_PROVIDER || 'mock') as AIProvider;
    const apiKey = process.env.NEXT_PUBLIC_AI_API_KEY || '';
    const model = process.env.NEXT_PUBLIC_AI_MODEL || 'gemini-1.5-flash';
    
    const config = { provider, apiKey, model };
    
    // Call AI transliteration API
    const result = await transliterate(config, {
      text,
      sourceLanguage: 'en',
      targetLanguage: 'hi',
    });
    
    return result.transliteratedText || text;
  } catch (error) {
    console.error('Error transliterating to Hindi:', error);
    return text; // Fallback to original text
  }
}

/**
 * Consolidate purposes by category for multiple items
 * Returns a single professional narrative for all items
 */
export async function consolidatePurposesByCategory(
  items: Array<{ productName: string; category?: string }>,
  language: 'hindi' | 'english' = 'hindi'
): Promise<string> {
  try {
    // Extract unique categories from items
    const categories = new Set<string>();
    items.forEach((item) => {
      if (item.category) {
        categories.add(item.category);
      }
    });
    
    if (categories.size === 0) {
      return language === 'hindi' ? TEMPORARY_PURPOSE_HINDI : TEMPORARY_PURPOSE_ENGLISH;
    }
    
    // Get professional purpose for each category
    const purposes = await Promise.all(
      Array.from(categories).map((category) => getPurposeByCategory(category, language))
    );
    
    // Consolidate purposes into a single narrative
    if (language === 'hindi') {
      if (purposes.length === 1) {
        return purposes[0];
      }
      // Join multiple purposes with "एवं" (and)
      return purposes.join(' एवं ');
    } else {
      if (purposes.length === 1) {
        return purposes[0];
      }
      // Join multiple purposes with "and"
      return purposes.join(' and ');
    }
  } catch (error) {
    console.error('Error consolidating purposes by category:', error);
    return language === 'hindi' ? TEMPORARY_PURPOSE_HINDI : TEMPORARY_PURPOSE_ENGLISH;
  }
}

/**
 * Extract category from item name
 * This is a simple implementation - can be enhanced based on business logic
 */
export function extractCategoryFromItemName(itemName: string): string {
  // Simple keyword-based category extraction
  const lowerName = itemName.toLowerCase();
  
  if (lowerName.includes('fire') || lowerName.includes('hose') || lowerName.includes('nozzle') || lowerName.includes('extinguisher')) {
    return 'fire_fighting';
  }
  if (lowerName.includes('water') || lowerName.includes('pipe') || lowerName.includes('tank')) {
    return 'water_supply';
  }
  if (lowerName.includes('chemical') || lowerName.includes('malathion') || lowerName.includes('sodium')) {
    return 'chemicals';
  }
  if (lowerName.includes('road') || lowerName.includes('cement') || lowerName.includes('construction')) {
    return 'construction';
  }
  if (lowerName.includes('stationery') || lowerName.includes('office') || lowerName.includes('furniture')) {
    return 'office_supplies';
  }
  
  // Default category
  return 'general';
}

/**
 * Automatically process bill items into itemHindiMappings collection with AI transliteration.
 * If AI generation fails, catches error gracefully and saves fallback without blocking.
 */
export async function saveBillItemMappings(
  items: Array<{ productName: string; description?: string }>
): Promise<void> {
  if (!items || items.length === 0) return;

  try {
    const existingMappings = await dataService.itemHindiMappings.list();

    for (const item of items) {
      const rawName = item.productName?.trim();
      const rawDescription = item.description?.trim() || '';
      if (!rawName) continue;

      const matched = existingMappings.find((m) =>
        (m.rawName && m.rawName.toLowerCase().trim() === rawName.toLowerCase()) ||
        m.englishName.toLowerCase().trim() === rawName.toLowerCase() ||
        m.hindiName.trim() === rawName
      );

      if (matched) {
        await dataService.itemHindiMappings.update(matched.id, {
          usageCount: (matched.usageCount || 0) + 1,
        });
      } else {
        let pack = {
          rawName,
          rawDescription,
          englishName: rawName,
          englishDescription: rawDescription,
          hindiName: rawName,
          hindiDescription: rawDescription,
          altHindiName: `${rawName} (वैकल्पिक 1)`,
          altHindiName2: `${rawName} (वैकल्पिक 2)`,
          altEnglishName1: `${rawName} Alt 1`,
          altEnglishName2: `${rawName} Alt 2`,
        };

        try {
          const res = await fetch('/api/ai/generate-alternates', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ rawName, rawDescription, itemName: rawName, description: rawDescription }),
          });
          if (res.ok) {
            const data = await res.json();
            pack = {
              rawName,
              rawDescription,
              englishName: data.englishName || rawName,
              englishDescription: data.englishDescription || rawDescription,
              hindiName: data.hindiName || rawName,
              hindiDescription: data.hindiDescription || rawDescription,
              altHindiName: data.altHindiName || data.altHindi || `${rawName} (वैकल्पिक 1)`,
              altHindiName2: data.altHindiName2 || `${rawName} (वैकल्पिक 2)`,
              altEnglishName1: data.altEnglishName1 || `${rawName} Alt 1`,
              altEnglishName2: data.altEnglishName2 || `${rawName} Alt 2`,
            };
          }
        } catch (aiErr) {
          console.warn('AI Mapping generation failed for item, using fallback:', rawName, aiErr);
        }

        await dataService.itemHindiMappings.create({
          ...pack,
          type: 'item' as const,
          usageCount: 1,
          isAutoGenerated: true,
        });
      }
    }
  } catch (err) {
    console.error('Error saving bill item mappings:', err);
  }
}

/**
 * Find or generate complete item mapping pack for an item.
 * If item name already exists in itemHindiMappings, reuses existing mapping WITHOUT triggering AI.
 * If new item, triggers AI generation via /api/ai/generate-alternates, saves it to itemHindiMappings, and returns it.
 */
export async function getOrCreateItemMappingPack(
  rawName: string,
  rawDescription?: string
): Promise<HindiMapping> {
  const trimmedName = rawName.trim();
  const trimmedDesc = rawDescription?.trim() || '';

  const existingMappings = await dataService.itemHindiMappings.list();
  const matched = existingMappings.find((m) =>
    (m.rawName && m.rawName.toLowerCase().trim() === trimmedName.toLowerCase()) ||
    m.englishName.toLowerCase().trim() === trimmedName.toLowerCase() ||
    m.hindiName.trim() === trimmedName
  );

  if (matched) {
    await dataService.itemHindiMappings.update(matched.id, {
      usageCount: (matched.usageCount || 0) + 1,
    });
    return {
      ...matched,
      usageCount: (matched.usageCount || 0) + 1,
    };
  }

  let pack = {
    rawName: trimmedName,
    rawDescription: trimmedDesc,
    englishName: trimmedName,
    englishDescription: trimmedDesc,
    hindiName: trimmedName,
    hindiDescription: trimmedDesc,
    altHindiName: `${trimmedName} (वैकल्पिक 1)`,
    altHindiName2: `${trimmedName} (वैकल्पिक 2)`,
    altEnglishName1: `${trimmedName} Alt 1`,
    altEnglishName2: `${trimmedName} Alt 2`,
  };

  try {
    const res = await fetch('/api/ai/generate-alternates', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        rawName: trimmedName,
        rawDescription: trimmedDesc,
        itemName: trimmedName,
        description: trimmedDesc,
      }),
    });

    if (res.ok) {
      const data = await res.json();
      pack = {
        rawName: trimmedName,
        rawDescription: trimmedDesc,
        englishName: data.englishName || trimmedName,
        englishDescription: data.englishDescription || trimmedDesc,
        hindiName: data.hindiName || trimmedName,
        hindiDescription: data.hindiDescription || trimmedDesc,
        altHindiName: data.altHindiName || data.altHindi || `${trimmedName} (वैकल्पिक 1)`,
        altHindiName2: data.altHindiName2 || `${trimmedName} (वैकल्पिक 2)`,
        altEnglishName1: data.altEnglishName1 || `${trimmedName} Alt 1`,
        altEnglishName2: data.altEnglishName2 || `${trimmedName} Alt 2`,
      };
    }
  } catch (err) {
    console.warn('AI Mapping generation failed, using fallback:', trimmedName, err);
  }

  const created = await dataService.itemHindiMappings.create({
    ...pack,
    type: 'item' as const,
    usageCount: 1,
    isAutoGenerated: true,
  });

  return created;
}
