import {
  DepartmentProfile,
  DocumentVersion,
  Firm,
  FirmStyleProfile,
  GSTRate,
  HindiMapping,
  AILocationCache,
  LetterheadFitMode,
  LocalBodyType,
  PlaceMapping,
  PurposeMapping,
  Settings,
  Tender,
  TenderDocType,
  TenderDocument,
  TenderItem,
  CustomTemplate,
  Bill,
} from '@/types';
import {
  Database,
  defaultLocalBodyTypes,
  defaultDatabase,
  defaultSettings,
  samplePlaceMappings,
  sampleDepartmentProfile,
  sampleFirms,
  DocumentPhraseMapping,
} from '@/data/schema';

import { normalizeSettingsVersioning } from '@/services/versioningSettings';
import { v4 as uuid } from 'uuid';

const DB_KEY = 'tender-automation-db';
const GST_SLABS: GSTRate[] = [0, 5, 9, 12, 18];
const DOC_TYPES: TenderDocType[] = [
  'vigyapti',
  'quotation_main',
  'quotation_alt_1',
  'quotation_alt_2',
  'supply_aadesh',
  'firm_bill',
];
const FIRM_STYLE_PROFILES: FirmStyleProfile[] = [
  'govt_formal',
  'minimal_business',
  'bilingual',
  'table_heavy',
];
const LETTERHEAD_FIT_MODES: LetterheadFitMode[] = ['contain', 'cover', 'stretch'];

function nowIso(): string {
  return new Date().toISOString();
}

function toSafeString(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback;
}

function toSafeNumber(value: unknown, fallback = 0): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback;
}

function toSafeBoolean(value: unknown, fallback = false): boolean {
  return typeof value === 'boolean' ? value : fallback;
}

function toSafeStampMode(value: unknown): 'image' | 'generic' {
  return value === 'generic' ? 'generic' : 'image';
}

function clampNumber(value: number, min: number, max: number): number {
  if (!Number.isFinite(value)) return min;
  return Math.min(max, Math.max(min, value));
}

function toSafeLanguage(value: unknown): 'hindi' | 'english' {
  return value === 'hindi' ? 'hindi' : 'english';
}

function toSafeGST(value: unknown): GSTRate {
  const numeric = toSafeNumber(value, 18) as GSTRate;
  return GST_SLABS.includes(numeric) ? numeric : 18;
}

function toSafeDocType(value: unknown): TenderDocType {
  return DOC_TYPES.includes(value as TenderDocType) ? (value as TenderDocType) : 'quotation_main';
}

function toSafeFirmStyle(value: unknown): FirmStyleProfile {
  return FIRM_STYLE_PROFILES.includes(value as FirmStyleProfile)
    ? (value as FirmStyleProfile)
    : 'govt_formal';
}

function toSafeFitMode(value: unknown): LetterheadFitMode {
  return LETTERHEAD_FIT_MODES.includes(value as LetterheadFitMode)
    ? (value as LetterheadFitMode)
    : 'contain';
}

function normalizeTenderItem(item: Partial<TenderItem>, tenderId: string): TenderItem {
  const quantity = Math.max(0, toSafeNumber(item.quantity, 1));
  const rate = Math.max(0, toSafeNumber(item.rate, 0));
  return {
    id: toSafeString(item.id, uuid()),
    tenderId,
    productName: toSafeString(item.productName || item.description, 'Untitled Item'),
    description: toSafeString(item.description, ''),
    quantity,
    unit: toSafeString(item.unit, 'piece'),
    rate,
    gstPercent: toSafeGST(item.gstPercent),
    estimatedAmount: toSafeNumber(item.estimatedAmount, undefined),
    totalAmount: Math.round(quantity * rate * 100) / 100,
    createdAt: toSafeString(item.createdAt, nowIso()),
    updatedAt: toSafeString(item.updatedAt, nowIso()),
  };
}

function normalizePurposeMapping(mapping: Partial<PurposeMapping>): PurposeMapping {
  return {
    id: toSafeString(mapping.id, uuid()),
    category: toSafeString(mapping.category, ''),
    professionalPurpose: toSafeString(mapping.professionalPurpose, ''),
    language: toSafeLanguage(mapping.language),
    usageCount: toSafeNumber(mapping.usageCount, 0),
    isAutoGenerated: toSafeBoolean(mapping.isAutoGenerated, false),
    createdAt: toSafeString(mapping.createdAt, nowIso()),
    updatedAt: toSafeString(mapping.updatedAt, nowIso()),
  };
}

function normalizeHindiMapping(mapping: Partial<HindiMapping>, type: 'item' | 'vendor'): HindiMapping {
  return {
    id: toSafeString(mapping.id, uuid()),
    rawName: toSafeString(mapping.rawName, ''),
    rawDescription: toSafeString(mapping.rawDescription, ''),
    englishName: toSafeString(mapping.englishName, ''),
    hindiName: toSafeString(mapping.hindiName, ''),
    englishDescription: toSafeString(mapping.englishDescription, ''),
    hindiDescription: toSafeString(mapping.hindiDescription, ''),
    altHindiName: toSafeString(mapping.altHindiName, ''),
    altHindiName2: toSafeString(mapping.altHindiName2, ''),
    altHindiName3: toSafeString(mapping.altHindiName3, ''),
    altHindiName4: toSafeString(mapping.altHindiName4, ''),
    altEnglishName1: toSafeString(mapping.altEnglishName1, ''),
    altEnglishName2: toSafeString(mapping.altEnglishName2, ''),
    altEnglishName3: toSafeString(mapping.altEnglishName3, ''),
    altEnglishName4: toSafeString(mapping.altEnglishName4, ''),
    altHindiDescription1: toSafeString(mapping.altHindiDescription1, ''),
    altHindiDescription2: toSafeString(mapping.altHindiDescription2, ''),
    altEnglishDescription1: toSafeString(mapping.altEnglishDescription1, ''),
    altEnglishDescription2: toSafeString(mapping.altEnglishDescription2, ''),
    type,
    usageCount: toSafeNumber(mapping.usageCount, 0),
    isAutoGenerated: toSafeBoolean(mapping.isAutoGenerated, false),
    createdAt: toSafeString(mapping.createdAt, nowIso()),
    updatedAt: toSafeString(mapping.updatedAt, nowIso()),
  };
}

function normalizePlaceMapping(mapping: Partial<PlaceMapping>): PlaceMapping {
  return {
    id: toSafeString(mapping.id, uuid()),
    englishName: toSafeString(mapping.englishName, ''),
    hindiName: toSafeString(mapping.hindiName, ''),
    districtName: toSafeString(mapping.districtName, ''),
    districtHindiName: toSafeString(mapping.districtHindiName, ''),
    stateName: toSafeString(mapping.stateName, 'Madhya Pradesh'),
    stateHindiName: toSafeString(mapping.stateHindiName, 'मध्य प्रदेश'),
    localBodyType: toSafeString(mapping.localBodyType, ''),
    localBodyTypeHindi: toSafeString(mapping.localBodyTypeHindi, ''),
    usageCount: toSafeNumber(mapping.usageCount, 0),
    isAutoGenerated: toSafeBoolean(mapping.isAutoGenerated, false),
    createdAt: toSafeString(mapping.createdAt, nowIso()),
    updatedAt: toSafeString(mapping.updatedAt, nowIso()),
  };
}

function normalizeLocalBodyType(bodyType: Partial<LocalBodyType>): LocalBodyType {
  return {
    id: toSafeString(bodyType.id, uuid()),
    englishName: toSafeString(bodyType.englishName, ''),
    hindiName: toSafeString(bodyType.hindiName, ''),
    usageCount: toSafeNumber(bodyType.usageCount, 0),
    isDefault: toSafeBoolean(bodyType.isDefault, false),
    createdAt: toSafeString(bodyType.createdAt, nowIso()),
    updatedAt: toSafeString(bodyType.updatedAt, nowIso()),
  };
}

function normalizeAILocationCache(entry: Partial<AILocationCache>): AILocationCache {
  return {
    id: toSafeString(entry.id, uuid()),
    query: toSafeString(entry.query, ''),
    englishName: toSafeString(entry.englishName, ''),
    hindiName: toSafeString(entry.hindiName, ''),
    districtName: toSafeString(entry.districtName, ''),
    districtHindiName: toSafeString(entry.districtHindiName, ''),
    stateName: toSafeString(entry.stateName, 'Madhya Pradesh'),
    stateHindiName: toSafeString(entry.stateHindiName, 'मध्य प्रदेश'),
    confidence: clampNumber(toSafeNumber(entry.confidence, 0.7), 0, 1),
    provider: toSafeString(entry.provider, 'local'),
    createdAt: toSafeString(entry.createdAt, nowIso()),
    updatedAt: toSafeString(entry.updatedAt, nowIso()),
  };
}

function normalizeCustomTemplate(template: Partial<CustomTemplate>): CustomTemplate {
  return {
    id: toSafeString(template.id, uuid()),
    name: toSafeString(template.name, 'Untitled Template'),
    docType: toSafeString(template.docType, 'quotation_main') as TenderDocType,
    language: toSafeLanguage(template.language),
    content: toSafeString(template.content, ''),
    fontFamily: toSafeString(template.fontFamily, 'Noto Sans Devanagari'),
    createdAt: toSafeString(template.createdAt, nowIso()),
    updatedAt: toSafeString(template.updatedAt, nowIso()),
  };
}

function normalizeBill(bill: Partial<Bill>): Bill {
  const items = Array.isArray(bill.items)
    ? bill.items.map((item) => ({
        id: toSafeString(item.id, uuid()),
        productName: toSafeString(item.productName, 'Item'),
        description: toSafeString(item.description, ''),
        quantity: toSafeNumber(item.quantity, 1),
        unit: toSafeString(item.unit, 'nos'),
        rate: toSafeNumber(item.rate, 0),
        amount: toSafeNumber(item.amount, (toSafeNumber(item.quantity, 1) * toSafeNumber(item.rate, 0))),
      }))
    : [];

  return {
    id: toSafeString(bill.id, uuid()),
    invoiceNumber: toSafeString(bill.invoiceNumber, ''),
    invoiceDate: toSafeString(bill.invoiceDate, new Date().toISOString().split('T')[0]),
    firmId: toSafeString(bill.firmId, ''),
    customTemplateId: toSafeString(bill.customTemplateId, ''),
    recipientDesignation: toSafeString(bill.recipientDesignation, 'Chief Municipal Officer'),
    recipientDepartment: toSafeString(bill.recipientDepartment, 'City Council'),
    recipientDistrict: toSafeString(bill.recipientDistrict, 'District'),
    recipientAddress: toSafeString(bill.recipientAddress, ''),
    items,
    sgstPercent: toSafeNumber(bill.sgstPercent, 9),
    cgstPercent: toSafeNumber(bill.cgstPercent, 9),
    igstPercent: toSafeNumber(bill.igstPercent, 0),
    totalAmount: toSafeNumber(bill.totalAmount, 0),
    sgstAmount: toSafeNumber(bill.sgstAmount, 0),
    cgstAmount: toSafeNumber(bill.cgstAmount, 0),
    igstAmount: toSafeNumber(bill.igstAmount, 0),
    grandTotal: toSafeNumber(bill.grandTotal, 0),
    amountInWords: toSafeString(bill.amountInWords, ''),
    status: bill.status === 'final' ? 'final' : 'draft',
    showLetterheadBackground: bill.showLetterheadBackground ?? true,
    includeSignature: bill.includeSignature ?? true,
    includeStamp: bill.includeStamp ?? true,
    notes: toSafeString(bill.notes, ''),
    createdAt: toSafeString(bill.createdAt, nowIso()),
    updatedAt: toSafeString(bill.updatedAt, nowIso()),
  };
}

function normalizeDocumentPhraseMapping(mapping: Partial<DocumentPhraseMapping>): DocumentPhraseMapping {
  return {
    id: toSafeString(mapping.id, uuid()),
    categoryName: toSafeString(mapping.categoryName, ''),
    categoryId: toSafeString(mapping.categoryId, ''),
    keywords: Array.isArray(mapping.keywords) ? mapping.keywords : [],
    phrases: mapping.phrases ?? {
      supplyOrder: { subject: '' },
      quotationMain: { english: '', hindi: '' },
      quotation: { purchaseLine: '' },
      quotationAltHindi: { subject: '' },
      quotationAltEnglish: { subject: '' },
      bill: { itemDescription: '' },
    },
    generatedByAI: toSafeBoolean(mapping.generatedByAI, false),
    approved: toSafeBoolean(mapping.approved, false),
    usageCount: toSafeNumber(mapping.usageCount, 0),
    lastUsedAt: mapping.lastUsedAt,
    englishDescription: toSafeString(mapping.englishDescription, ''),
    createdAt: toSafeString(mapping.createdAt, nowIso()),
    updatedAt: toSafeString(mapping.updatedAt, nowIso()),
  };
}

function normalizeFirm(
  firm: Partial<Firm> & {
    marginTopPx?: number;
    marginLeftPx?: number;
    letterStartMarginTop?: number;
    letterStartMarginLeft?: number;
    headerSpacing?: number;
    footerSpacing?: number;
    pageMargin?: number;
    layoutReferenceWidth?: number;
    contentStartY?: number;
    pagePaddingLeft?: number;
    signatureOffsetX?: number;
    signatureOffsetY?: number;
    signatureScale?: number;
    signatureRotateDeg?: number;
    stampOffsetX?: number;
    stampOffsetY?: number;
    stampScale?: number;
    stampMode?: unknown;
    fitLetterheadMode?: string;
    firmStyleProfile?: string;
  }
): Firm {
  // Migration path:
  // 1) Prefer new simplified fields when present.
  // 2) Fallback to old contentStartY/pagePaddingLeft (and older aliases) when missing.
  const legacyContentStartY = Math.max(
    0,
    toSafeNumber(firm.contentStartY ?? firm.letterStartMarginTop ?? firm.marginTopPx, 170)
  );
  const legacyPaddingLeft = Math.max(
    0,
    toSafeNumber(firm.pagePaddingLeft ?? firm.letterStartMarginLeft ?? firm.marginLeftPx, 40)
  );

  const headerSpacing = clampNumber(toSafeNumber(firm.headerSpacing, legacyContentStartY), 80, 300);
  const footerSpacing = clampNumber(toSafeNumber(firm.footerSpacing, 120), 40, 220);
  const pageMargin = clampNumber(toSafeNumber(firm.pageMargin, legacyPaddingLeft), 20, 100);
  const layoutReferenceWidth = clampNumber(toSafeNumber(firm.layoutReferenceWidth, 424), 1, 2000);

  const signatureOffsetX = clampNumber(toSafeNumber(firm.signatureOffsetX, 16), 0, 240);
  const signatureOffsetY = clampNumber(toSafeNumber(firm.signatureOffsetY, 16), 0, 240);
  const signatureScale = clampNumber(toSafeNumber(firm.signatureScale, 1), 0.4, 2.2);
  const signatureRotateDeg = clampNumber(toSafeNumber(firm.signatureRotateDeg, 0), -45, 45);
  const stampOffsetX = clampNumber(toSafeNumber(firm.stampOffsetX, 140), 0, 320);
  const stampOffsetY = clampNumber(toSafeNumber(firm.stampOffsetY, 16), 0, 240);
  const stampScale = clampNumber(toSafeNumber(firm.stampScale, 1), 0.4, 2.2);
  const stampMode = toSafeStampMode(firm.stampMode);

  return {
    id: toSafeString(firm.id, uuid()),
    name: toSafeString(firm.name, 'Untitled Firm'),
    headerImagePath: toSafeString(firm.headerImagePath, ''),
    signatureImagePath: toSafeString(firm.signatureImagePath, ''),
    stampImagePath: toSafeString(firm.stampImagePath, ''),
    defaultLanguage: toSafeLanguage(firm.defaultLanguage),
    fitLetterheadMode: toSafeFitMode(firm.fitLetterheadMode),
    headerSpacing,
    footerSpacing,
    pageMargin,
    layoutReferenceWidth,
    // Keep legacy fields populated so older exports or modules that still read them won't break.
    contentStartY: legacyContentStartY,
    pagePaddingLeft: legacyPaddingLeft,
    signatureOffsetX,
    signatureOffsetY,
    signatureScale,
    signatureRotateDeg,
    stampOffsetX,
    stampOffsetY,
    stampScale,
    stampMode,
    aiPromptQuotation: toSafeString(firm.aiPromptQuotation, ''),
    aiPromptBill: toSafeString(firm.aiPromptBill, ''),
    firmStyleProfile: toSafeFirmStyle(firm.firmStyleProfile),
    firmCity: toSafeString(firm.firmCity, ''),
    firmAddress: toSafeString(firm.firmAddress, ''),
    gstNumber: toSafeString(firm.gstNumber, ''),
    mobileNumber: toSafeString(firm.mobileNumber, ''),
    contactPerson: toSafeString(firm.contactPerson, ''),
    vendorHindiName: toSafeString(firm.vendorHindiName, ''),
    bankName: toSafeString(firm.bankName, ''),
    bankBranch: toSafeString(firm.bankBranch, ''),
    ifscCode: toSafeString(firm.ifscCode, ''),
    accountNumber: toSafeString(firm.accountNumber, ''),
    panNumber: toSafeString(firm.panNumber, ''),
    billInstructions: toSafeString(firm.billInstructions, ''),
    customQuotationTemplateId: toSafeString(firm.customQuotationTemplateId, ''),
    createdAt: toSafeString(firm.createdAt, nowIso()),
    updatedAt: toSafeString(firm.updatedAt, nowIso()),
  };
}

function normalizeTender(raw: Partial<Tender> & { status?: string }): Tender {
  const id = toSafeString(raw.id, uuid());
  const status = raw.status === 'draft' ? 'draft' : 'final';
  const items = Array.isArray(raw.items) ? raw.items : [];

  return {
    id,
    title: toSafeString(raw.title, 'Untitled Tender'),
    tenderNumber: toSafeString(raw.tenderNumber, `TEND-${Date.now()}`),
    departmentProfileId: toSafeString(raw.departmentProfileId, 'dept-1'),
    mainFirmId: toSafeString(raw.mainFirmId, ''),
    alternateFirms: Array.isArray(raw.alternateFirms)
      ? raw.alternateFirms.filter((value): value is string => typeof value === 'string').slice(0, 2)
      : [],
    items: items.map((item) => normalizeTenderItem((item as Partial<TenderItem>) || {}, id)),
    language: toSafeLanguage(raw.language),
    status,
    description: toSafeString(raw.description, ''),
    notes: toSafeString(raw.notes, ''),
    version: Math.max(1, toSafeNumber(raw.version, 1)),
    parentTenderId: toSafeString(raw.parentTenderId, ''),
    tenderType: toSafeString(raw.tenderType, ''),
    placeName: toSafeString(raw.placeName, ''),
    districtName: toSafeString(raw.districtName, ''),
    localBodyType: toSafeString(raw.localBodyType, ''),
    localBodyTypeHindi: toSafeString(raw.localBodyTypeHindi, ''),
    publishDate: toSafeString(raw.publishDate, ''),
    submissionDate: toSafeString(raw.submissionDate, ''),
    openingDate: toSafeString(raw.openingDate, ''),
    estimatedBudget: toSafeNumber(raw.estimatedBudget, undefined),
    estimatedAmount: toSafeNumber(raw.estimatedAmount, undefined),
    createdAt: toSafeString(raw.createdAt, nowIso()),
    updatedAt: toSafeString(raw.updatedAt, nowIso()),
  };
}

function normalizeDocument(
  raw: Partial<TenderDocument> & { includeLogo?: boolean; showSafeMarginGuide?: boolean; lockHeaderPosition?: boolean },
  tenderIdFallback = ''
): TenderDocument {
  return {
    id: toSafeString(raw.id, uuid()),
    tenderId: toSafeString(raw.tenderId, tenderIdFallback),
    docType: toSafeDocType(raw.docType),
    contentHTML: toSafeString(raw.contentHTML, ''),
    pdfPath: toSafeString(raw.pdfPath, ''),
    lastModified: toSafeString(raw.lastModified, ''),
    currentVersion: Math.max(1, toSafeNumber(raw.currentVersion, 1)),
    versions: Array.isArray(raw.versions) ? raw.versions : [],
    showLetterheadBackground: toSafeBoolean(raw.showLetterheadBackground ?? raw.includeLogo, true),
    showSafeMarginGuide: toSafeBoolean(raw.showSafeMarginGuide, false),
    lockHeaderPosition: toSafeBoolean(raw.lockHeaderPosition, true),
    includeSignature: toSafeBoolean(raw.includeSignature, false),
    includeStamp: toSafeBoolean(raw.includeStamp, false),
    footerNotes: toSafeString(raw.footerNotes, ''),
    overflowWarning: toSafeString(raw.overflowWarning, ''),
    createdAt: toSafeString(raw.createdAt, nowIso()),
    updatedAt: toSafeString(raw.updatedAt, nowIso()),
  };
}

function normalizeSettings(raw: Partial<Settings> | undefined): Settings {
  if (!raw) return normalizeSettingsVersioning({ ...defaultSettings });
  return normalizeSettingsVersioning({
    ...defaultSettings,
    ...raw,
    defaultLanguage: toSafeLanguage(raw.defaultLanguage),
    createdAt: toSafeString(raw.createdAt, defaultSettings.createdAt),
    updatedAt: toSafeString(raw.updatedAt, nowIso()),
  });
}

function normalizeDatabase(raw: unknown): Database {
  const parsed = (raw || {}) as Partial<Database>;
  const tenders = Array.isArray(parsed.tenders)
    ? parsed.tenders.map((tender) => normalizeTender(tender as Tender))
    : [];
  const firms = Array.isArray(parsed.firms)
    ? parsed.firms.map((firm) =>
        normalizeFirm(
          firm as Partial<Firm> & {
            marginTopPx?: number;
            marginLeftPx?: number;
            letterStartMarginTop?: number;
            letterStartMarginLeft?: number;
            contentStartY?: number;
            pagePaddingLeft?: number;
            fitLetterheadMode?: string;
            firmStyleProfile?: string;
          }
        )
      )
    : [];
  const documents = Array.isArray(parsed.documents)
    ? parsed.documents.map((document) => normalizeDocument(document as TenderDocument))
    : [];
  const purposeMappings = Array.isArray(parsed.purposeMappings)
    ? parsed.purposeMappings.map((mapping) => normalizePurposeMapping(mapping))
    : [];
  const itemHindiMappings = Array.isArray(parsed.itemHindiMappings)
    ? parsed.itemHindiMappings.map((mapping) => normalizeHindiMapping(mapping, 'item'))
    : [];
  const vendorHindiMappings = Array.isArray(parsed.vendorHindiMappings)
    ? parsed.vendorHindiMappings.map((mapping) => normalizeHindiMapping(mapping, 'vendor'))
    : [];
  const placeMappings = Array.isArray(parsed.placeMappings)
    ? parsed.placeMappings.map((mapping) => normalizePlaceMapping(mapping))
    : [];
  const localBodyTypes = Array.isArray(parsed.localBodyTypes)
    ? parsed.localBodyTypes.map((bodyType) => normalizeLocalBodyType(bodyType))
    : [];
  const aiLocationCache = Array.isArray(parsed.aiLocationCache)
    ? parsed.aiLocationCache.map((entry) => normalizeAILocationCache(entry))
    : [];

  const customTemplates = Array.isArray(parsed.customTemplates)
    ? parsed.customTemplates.map((t) => normalizeCustomTemplate(t))
    : [];

  return {
    tenders,
    firms: firms.length > 0 ? firms : [...sampleFirms],
    documents,
    settings: [normalizeSettings(Array.isArray(parsed.settings) ? parsed.settings[0] : undefined)],
    departmentProfiles:
      Array.isArray(parsed.departmentProfiles) && parsed.departmentProfiles.length > 0
        ? parsed.departmentProfiles
        : [sampleDepartmentProfile],
    documentVersions: Array.isArray(parsed.documentVersions) ? parsed.documentVersions : [],
    purposeMappings,
    itemHindiMappings,
    vendorHindiMappings,
    placeMappings: placeMappings.length > 0 ? placeMappings : [...samplePlaceMappings],
    localBodyTypes: localBodyTypes.length > 0 ? localBodyTypes : [...defaultLocalBodyTypes],
    aiLocationCache,
    documentPhraseMappings: Array.isArray(parsed.documentPhraseMappings)
      ? parsed.documentPhraseMappings.map((m: any) => normalizeDocumentPhraseMapping(m))
      : [],
    customTemplates,
    bills: Array.isArray(parsed.bills) ? parsed.bills.map((b: any) => normalizeBill(b)) : [],
  };
}


class LocalStorageDB {
  private db: Database;

  constructor() {
    this.db = this.loadDatabase();
  }

  private loadDatabase(): Database {
    if (typeof window === 'undefined') {
      return { ...defaultDatabase };
    }

    try {
      const stored = localStorage.getItem(DB_KEY);
      if (!stored) {
        const initial: Database = {
          ...defaultDatabase,
          settings: [{ ...defaultSettings }],
          firms: [...sampleFirms],
          departmentProfiles: [sampleDepartmentProfile],
          placeMappings: [...samplePlaceMappings],
          localBodyTypes: [...defaultLocalBodyTypes],
          customTemplates: [],
        };
        this.saveToStorage(initial);
        return initial;
      }
      const normalized = normalizeDatabase(JSON.parse(stored));
      this.saveToStorage(normalized);
      return normalized;
    } catch {
      const fallback: Database = {
        ...defaultDatabase,
        settings: [{ ...defaultSettings }],
        firms: [...sampleFirms],
        departmentProfiles: [sampleDepartmentProfile],
        placeMappings: [...samplePlaceMappings],
        localBodyTypes: [...defaultLocalBodyTypes],
      };
      this.saveToStorage(fallback);
      return fallback;
    }
  }

  private saveToStorage(db: Database): void {
    if (typeof window === 'undefined') return;
    localStorage.setItem(DB_KEY, JSON.stringify(db));
    this.db = db;
  }

  getDatabase(): Database {
    return this.db;
  }

  createTender(data: Omit<Tender, 'id' | 'createdAt' | 'updatedAt'>): Tender {
    const tenderId = uuid();
    const createdAt = nowIso();
    const tender: Tender = {
      ...data,
      id: tenderId,
      items: (data.items || []).map((item) => normalizeTenderItem(item, tenderId)),
      status: data.status === 'draft' ? 'draft' : 'final',
      createdAt,
      updatedAt: createdAt,
    };
    this.db.tenders.push(tender);
    this.saveToStorage(this.db);
    return tender;
  }

  getTender(id: string): Tender | undefined {
    return this.db.tenders.find((tender) => tender.id === id);
  }

  listTenders(): Tender[] {
    return [...this.db.tenders].sort(
      (left, right) => new Date(right.createdAt).getTime() - new Date(left.createdAt).getTime()
    );
  }

  updateTender(id: string, data: Partial<Omit<Tender, 'id' | 'createdAt'>>): Tender | undefined {
    const index = this.db.tenders.findIndex((tender) => tender.id === id);
    if (index === -1) return undefined;

    const current = this.db.tenders[index];
    const items = Array.isArray(data.items)
      ? data.items.map((item) => normalizeTenderItem(item, id))
      : current.items;

    const updated: Tender = {
      ...current,
      ...data,
      items,
      status: data.status ? (data.status === 'draft' ? 'draft' : 'final') : current.status,
      updatedAt: nowIso(),
    };

    this.db.tenders[index] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  deleteTender(id: string): boolean {
    const index = this.db.tenders.findIndex((tender) => tender.id === id);
    if (index === -1) return false;

    this.db.tenders.splice(index, 1);
    this.db.documents = this.db.documents.filter((document) => document.tenderId !== id);
    this.saveToStorage(this.db);
    return true;
  }

  createFirm(data: Omit<Firm, 'id' | 'createdAt' | 'updatedAt'>): Firm {
    const createdAt = nowIso();
    const firm: Firm = {
      ...normalizeFirm(data),
      id: uuid(),
      createdAt,
      updatedAt: createdAt,
    };
    this.db.firms.push(firm);
    this.saveToStorage(this.db);
    return firm;
  }

  getFirm(id: string): Firm | undefined {
    return this.db.firms.find((firm) => firm.id === id);
  }

  listFirms(): Firm[] {
    return [...this.db.firms];
  }

  updateFirm(id: string, data: Partial<Omit<Firm, 'id' | 'createdAt'>>): Firm | undefined {
    const index = this.db.firms.findIndex((firm) => firm.id === id);
    if (index === -1) return undefined;

    const updated = normalizeFirm({
      ...this.db.firms[index],
      ...data,
      id,
      updatedAt: nowIso(),
    });
    this.db.firms[index] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  deleteFirm(id: string): boolean {
    const index = this.db.firms.findIndex((firm) => firm.id === id);
    if (index === -1) return false;
    this.db.firms.splice(index, 1);
    this.saveToStorage(this.db);
    return true;
  }

  createDocument(data: Omit<TenderDocument, 'id' | 'createdAt' | 'updatedAt'>): TenderDocument {
    const createdAt = nowIso();
    const document: TenderDocument = {
      ...normalizeDocument(data),
      id: uuid(),
      createdAt,
      updatedAt: createdAt,
    };
    this.db.documents.push(document);
    this.saveToStorage(this.db);
    return document;
  }

  getDocument(id: string): TenderDocument | undefined {
    return this.db.documents.find((document) => document.id === id);
  }

  listDocumentsByTender(tenderId: string): TenderDocument[] {
    return this.db.documents.filter((document) => document.tenderId === tenderId);
  }

  updateDocument(id: string, data: Partial<Omit<TenderDocument, 'id' | 'createdAt'>>): TenderDocument | undefined {
    const index = this.db.documents.findIndex((document) => document.id === id);
    if (index === -1) return undefined;
    const updated = normalizeDocument({
      ...this.db.documents[index],
      ...data,
      id,
      updatedAt: nowIso(),
    });
    this.db.documents[index] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  deleteDocument(id: string): boolean {
    const index = this.db.documents.findIndex((document) => document.id === id);
    if (index === -1) return false;
    this.db.documents.splice(index, 1);
    this.saveToStorage(this.db);
    return true;
  }

  getSettings(): Settings {
    const settings = normalizeSettings(this.db.settings[0] || defaultSettings);
    this.db.settings[0] = settings;
    return settings;
  }

  updateSettings(data: Partial<Omit<Settings, 'id' | 'createdAt'>>): Settings {
    const current = normalizeSettings(this.db.settings[0] || defaultSettings);
    const updated = normalizeSettings({
      ...current,
      ...data,
      updatedAt: nowIso(),
    });
    this.db.settings[0] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  createDepartmentProfile(data: Omit<DepartmentProfile, 'id' | 'createdAt' | 'updatedAt'>): DepartmentProfile {
    const createdAt = nowIso();
    const profile: DepartmentProfile = {
      ...data,
      id: uuid(),
      createdAt,
      updatedAt: createdAt,
    };
    this.db.departmentProfiles.push(profile);
    this.saveToStorage(this.db);
    return profile;
  }

  getDepartmentProfile(id: string): DepartmentProfile | undefined {
    return this.db.departmentProfiles.find((profile) => profile.id === id);
  }

  listDepartmentProfiles(): DepartmentProfile[] {
    return [...this.db.departmentProfiles].sort((left, right) => left.name.localeCompare(right.name));
  }

  updateDepartmentProfile(
    id: string,
    data: Partial<Omit<DepartmentProfile, 'id' | 'createdAt'>>
  ): DepartmentProfile | undefined {
    const index = this.db.departmentProfiles.findIndex((profile) => profile.id === id);
    if (index === -1) return undefined;

    const updated: DepartmentProfile = {
      ...this.db.departmentProfiles[index],
      ...data,
      updatedAt: nowIso(),
    };
    this.db.departmentProfiles[index] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  deleteDepartmentProfile(id: string): boolean {
    const index = this.db.departmentProfiles.findIndex((profile) => profile.id === id);
    if (index === -1) return false;
    this.db.departmentProfiles.splice(index, 1);
    this.saveToStorage(this.db);
    return true;
  }

  createTenderItem(data: Omit<TenderItem, 'id' | 'createdAt' | 'updatedAt'>): TenderItem {
    const tender = this.db.tenders.find((entry) => entry.id === data.tenderId);
    if (!tender) throw new Error('Parent tender not found for item');
    const item = normalizeTenderItem({ ...data, id: uuid(), createdAt: nowIso(), updatedAt: nowIso() }, data.tenderId);
    tender.items.push(item);
    tender.updatedAt = nowIso();
    this.saveToStorage(this.db);
    return item;
  }

  getTenderItem(id: string): TenderItem | undefined {
    for (const tender of this.db.tenders) {
      const item = tender.items.find((entry) => entry.id === id);
      if (item) return item;
    }
    return undefined;
  }

  listTenderItems(tenderId: string): TenderItem[] {
    return this.db.tenders.find((entry) => entry.id === tenderId)?.items || [];
  }

  updateTenderItem(id: string, data: Partial<Omit<TenderItem, 'id' | 'createdAt'>>): TenderItem | undefined {
    for (const tender of this.db.tenders) {
      const index = tender.items.findIndex((item) => item.id === id);
      if (index !== -1) {
        const updated = normalizeTenderItem({ ...tender.items[index], ...data, updatedAt: nowIso() }, tender.id);
        tender.items[index] = updated;
        tender.updatedAt = nowIso();
        this.saveToStorage(this.db);
        return updated;
      }
    }
    return undefined;
  }

  deleteTenderItem(id: string): boolean {
    for (const tender of this.db.tenders) {
      const index = tender.items.findIndex((item) => item.id === id);
      if (index !== -1) {
        tender.items.splice(index, 1);
        tender.updatedAt = nowIso();
        this.saveToStorage(this.db);
        return true;
      }
    }
    return false;
  }

  createDocumentVersion(data: Omit<DocumentVersion, 'id' | 'createdAt' | 'updatedAt'>): DocumentVersion {
    const createdAt = nowIso();
    const version: DocumentVersion = {
      ...data,
      id: uuid(),
      createdAt,
      updatedAt: createdAt,
    };
    this.db.documentVersions.push(version);
    this.saveToStorage(this.db);
    return version;
  }

  getDocumentVersions(documentId: string): DocumentVersion[] {
    return this.db.documentVersions
      .filter((version) => version.documentId === documentId)
      .sort((left, right) => right.versionNumber - left.versionNumber);
  }

  deleteDocumentVersions(documentId: string): boolean {
    const initial = this.db.documentVersions.length;
    this.db.documentVersions = this.db.documentVersions.filter((version) => version.documentId !== documentId);
    if (this.db.documentVersions.length < initial) {
      this.saveToStorage(this.db);
      return true;
    }
    return false;
  }

  deleteDocumentVersion(documentId: string, versionId: string): boolean {
    const initial = this.db.documentVersions.length;
    this.db.documentVersions = this.db.documentVersions.filter(
      (version) => !(version.documentId === documentId && version.id === versionId)
    );
    if (this.db.documentVersions.length < initial) {
      this.saveToStorage(this.db);
      return true;
    }
    return false;
  }

  updateDocumentVersion(
    documentId: string,
    versionId: string,
    data: Partial<Omit<DocumentVersion, 'id' | 'createdAt' | 'documentId'>>
  ): DocumentVersion | undefined {
    const index = this.db.documentVersions.findIndex(
      (version) => version.documentId === documentId && version.id === versionId
    );
    if (index === -1) return undefined;
    const updated: DocumentVersion = {
      ...this.db.documentVersions[index],
      ...data,
      updatedAt: nowIso(),
    };
    this.db.documentVersions[index] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  exportDatabase(): string {
    return JSON.stringify(this.db, null, 2);
  }

  importDatabase(data: string): boolean {
    try {
      const imported = normalizeDatabase(JSON.parse(data));
      this.saveToStorage(imported);
      return true;
    } catch {
      return false;
    }
  }

  clearDatabase(): void {
    const initial: Database = {
      ...defaultDatabase,
      settings: [{ ...defaultSettings }],
      firms: [...sampleFirms],
      departmentProfiles: [sampleDepartmentProfile],
      purposeMappings: [],
      itemHindiMappings: [],
      vendorHindiMappings: [],
      placeMappings: [...samplePlaceMappings],
      localBodyTypes: [...defaultLocalBodyTypes],
      aiLocationCache: [],
      customTemplates: [],
    };
    this.saveToStorage(initial);
  }

  createPlaceMapping(data: Omit<PlaceMapping, 'id' | 'createdAt' | 'updatedAt'>): PlaceMapping {
    const createdAt = nowIso();
    const mapping = normalizePlaceMapping({ ...data, id: uuid(), createdAt, updatedAt: createdAt });
    this.db.placeMappings.push(mapping);
    this.saveToStorage(this.db);
    return mapping;
  }

  listPlaceMappings(): PlaceMapping[] {
    return [...this.db.placeMappings].sort((left, right) => right.usageCount - left.usageCount);
  }

  updatePlaceMapping(id: string, data: Partial<Omit<PlaceMapping, 'id' | 'createdAt'>>): PlaceMapping | undefined {
    const index = this.db.placeMappings.findIndex((mapping) => mapping.id === id);
    if (index === -1) return undefined;
    const updated = normalizePlaceMapping({ ...this.db.placeMappings[index], ...data, id, updatedAt: nowIso() });
    this.db.placeMappings[index] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  deletePlaceMapping(id: string): boolean {
    const index = this.db.placeMappings.findIndex((mapping) => mapping.id === id);
    if (index === -1) return false;
    this.db.placeMappings.splice(index, 1);
    this.saveToStorage(this.db);
    return true;
  }

  createLocalBodyType(data: Omit<LocalBodyType, 'id' | 'createdAt' | 'updatedAt'>): LocalBodyType {
    const createdAt = nowIso();
    const bodyType = normalizeLocalBodyType({ ...data, id: uuid(), createdAt, updatedAt: createdAt });
    this.db.localBodyTypes.push(bodyType);
    this.saveToStorage(this.db);
    return bodyType;
  }

  listLocalBodyTypes(): LocalBodyType[] {
    return [...this.db.localBodyTypes].sort((left, right) => Number(right.isDefault) - Number(left.isDefault));
  }

  updateLocalBodyType(
    id: string,
    data: Partial<Omit<LocalBodyType, 'id' | 'createdAt'>>
  ): LocalBodyType | undefined {
    const index = this.db.localBodyTypes.findIndex((bodyType) => bodyType.id === id);
    if (index === -1) return undefined;
    const updated = normalizeLocalBodyType({ ...this.db.localBodyTypes[index], ...data, id, updatedAt: nowIso() });
    this.db.localBodyTypes[index] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  getAILocationCache(query: string): AILocationCache | undefined {
    const normalizedQuery = query.trim().toLowerCase();
    return this.db.aiLocationCache.find((entry) => entry.query.trim().toLowerCase() === normalizedQuery);
  }

  setAILocationCache(data: Omit<AILocationCache, 'id' | 'createdAt' | 'updatedAt'>): AILocationCache {
    const existing = this.getAILocationCache(data.query);
    if (existing) {
      return this.updateAILocationCache(existing.id, data) || existing;
    }
    const createdAt = nowIso();
    const entry = normalizeAILocationCache({ ...data, id: uuid(), createdAt, updatedAt: createdAt });
    this.db.aiLocationCache.push(entry);
    this.saveToStorage(this.db);
    return entry;
  }

  private updateAILocationCache(
    id: string,
    data: Partial<Omit<AILocationCache, 'id' | 'createdAt'>>
  ): AILocationCache | undefined {
    const index = this.db.aiLocationCache.findIndex((entry) => entry.id === id);
    if (index === -1) return undefined;
    const updated = normalizeAILocationCache({ ...this.db.aiLocationCache[index], ...data, id, updatedAt: nowIso() });
    this.db.aiLocationCache[index] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  // Purpose Mappings CRUD
  createPurposeMapping(data: Omit<PurposeMapping, 'id' | 'createdAt' | 'updatedAt'>): PurposeMapping {
    const createdAt = nowIso();
    const mapping: PurposeMapping = {
      ...data,
      id: uuid(),
      createdAt,
      updatedAt: createdAt,
    };
    this.db.purposeMappings.push(mapping);
    this.saveToStorage(this.db);
    return mapping;
  }

  getPurposeByCategory(category: string, language: 'hindi' | 'english'): PurposeMapping | undefined {
    return this.db.purposeMappings.find(
      (mapping) => mapping.category === category && mapping.language === language
    );
  }

  listPurposeMappings(): PurposeMapping[] {
    return [...this.db.purposeMappings];
  }

  updatePurposeMapping(
    id: string,
    data: Partial<Omit<PurposeMapping, 'id' | 'createdAt'>>
  ): PurposeMapping | undefined {
    const index = this.db.purposeMappings.findIndex((mapping) => mapping.id === id);
    if (index === -1) return undefined;

    const updated: PurposeMapping = {
      ...this.db.purposeMappings[index],
      ...data,
      updatedAt: nowIso(),
    };
    this.db.purposeMappings[index] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  deletePurposeMapping(id: string): boolean {
    const index = this.db.purposeMappings.findIndex((mapping) => mapping.id === id);
    if (index === -1) return false;
    this.db.purposeMappings.splice(index, 1);
    this.saveToStorage(this.db);
    return true;
  }

  // Item Hindi Mappings CRUD
  createItemHindiMapping(data: Omit<HindiMapping, 'id' | 'createdAt' | 'updatedAt'>): HindiMapping {
    const createdAt = nowIso();
    const mapping: HindiMapping = {
      ...data,
      id: uuid(),
      createdAt,
      updatedAt: createdAt,
    };
    this.db.itemHindiMappings.push(mapping);
    this.saveToStorage(this.db);
    return mapping;
  }

  getItemHindiMapping(englishName: string): HindiMapping | undefined {
    return this.db.itemHindiMappings.find((mapping) => mapping.englishName === englishName);
  }

  listItemHindiMappings(): HindiMapping[] {
    return [...this.db.itemHindiMappings];
  }

  updateItemHindiMapping(
    id: string,
    data: Partial<Omit<HindiMapping, 'id' | 'createdAt'>>
  ): HindiMapping | undefined {
    const index = this.db.itemHindiMappings.findIndex((mapping) => mapping.id === id);
    if (index === -1) return undefined;

    const updated: HindiMapping = {
      ...this.db.itemHindiMappings[index],
      ...data,
      updatedAt: nowIso(),
    };
    this.db.itemHindiMappings[index] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  deleteItemHindiMapping(id: string): boolean {
    const index = this.db.itemHindiMappings.findIndex((mapping) => mapping.id === id);
    if (index === -1) return false;
    this.db.itemHindiMappings.splice(index, 1);
    this.saveToStorage(this.db);
    return true;
  }

  // Vendor Hindi Mappings CRUD
  createVendorHindiMapping(data: Omit<HindiMapping, 'id' | 'createdAt' | 'updatedAt'>): HindiMapping {
    const createdAt = nowIso();
    const mapping: HindiMapping = {
      ...data,
      id: uuid(),
      createdAt,
      updatedAt: createdAt,
    };
    this.db.vendorHindiMappings.push(mapping);
    this.saveToStorage(this.db);
    return mapping;
  }

  getVendorHindiMapping(englishName: string): HindiMapping | undefined {
    return this.db.vendorHindiMappings.find((mapping) => mapping.englishName === englishName);
  }

  listVendorHindiMappings(): HindiMapping[] {
    return [...this.db.vendorHindiMappings];
  }

  listVendorHindiMappingsByType(type: 'item' | 'vendor'): HindiMapping[] {
    return this.db.vendorHindiMappings.filter((mapping) => mapping.type === type);
  }

  updateVendorHindiMapping(
    id: string,
    data: Partial<Omit<HindiMapping, 'id' | 'createdAt'>>
  ): HindiMapping | undefined {
    const index = this.db.vendorHindiMappings.findIndex((mapping) => mapping.id === id);
    if (index === -1) return undefined;

    const updated: HindiMapping = {
      ...this.db.vendorHindiMappings[index],
      ...data,
      updatedAt: nowIso(),
    };
    this.db.vendorHindiMappings[index] = updated;
    this.saveToStorage(this.db);
    return updated;
  }

  deleteVendorHindiMapping(id: string): boolean {
    const index = this.db.vendorHindiMappings.findIndex((mapping) => mapping.id === id);
    if (index === -1) return false;
    this.db.vendorHindiMappings.splice(index, 1);
    this.saveToStorage(this.db);
    return true;
  }

  // ─── Document Phrase Mappings CRUD ────────────────────────────────────────

  createDocumentPhraseMapping(
    data: Omit<DocumentPhraseMapping, 'id' | 'createdAt' | 'updatedAt'>
  ): DocumentPhraseMapping {
    const createdAt = nowIso();
    const mapping = normalizeDocumentPhraseMapping({ ...data, id: uuid(), createdAt, updatedAt: createdAt });
    if (!this.db.documentPhraseMappings) this.db.documentPhraseMappings = [];
    this.db.documentPhraseMappings.push(mapping);
    this.saveToStorage(this.db);
    return mapping;
  }

  getDocumentPhraseMappingByCategory(categoryId: string): DocumentPhraseMapping | undefined {
    return (this.db.documentPhraseMappings || []).find(
      (m) => m.categoryId === categoryId
    );
  }

  findDocumentPhraseMappingByKeyword(keyword: string): DocumentPhraseMapping | undefined {
    const normalizedKeyword = keyword.trim().toLowerCase();
    return (this.db.documentPhraseMappings || []).find(
      (m) =>
        m.categoryId === normalizedKeyword ||
        m.categoryName.toLowerCase() === normalizedKeyword ||
        m.keywords.some((k) => k.toLowerCase() === normalizedKeyword)
    );
  }

  listDocumentPhraseMappings(): DocumentPhraseMapping[] {
    return [...(this.db.documentPhraseMappings || [])].sort(
      (a, b) => b.usageCount - a.usageCount
    );
  }

  updateDocumentPhraseMapping(
    id: string,
    data: Partial<Omit<DocumentPhraseMapping, 'id' | 'createdAt'>>
  ): DocumentPhraseMapping | undefined {
    const arr = this.db.documentPhraseMappings || [];
    const index = arr.findIndex((m) => m.id === id);
    if (index === -1) return undefined;
    const updated = normalizeDocumentPhraseMapping({ ...arr[index], ...data, id, updatedAt: nowIso() });
    arr[index] = updated;
    this.db.documentPhraseMappings = arr;
    this.saveToStorage(this.db);
    return updated;
  }

  deleteDocumentPhraseMapping(id: string): boolean {
    const arr = this.db.documentPhraseMappings || [];
    const index = arr.findIndex((m) => m.id === id);
    if (index === -1) return false;
    arr.splice(index, 1);
    this.db.documentPhraseMappings = arr;
    this.saveToStorage(this.db);
    return true;
  }

  // Custom Templates CRUD
  createCustomTemplate(data: Omit<CustomTemplate, 'id' | 'createdAt' | 'updatedAt'>): CustomTemplate {
    const createdAt = nowIso();
    const template = normalizeCustomTemplate({ ...data, id: uuid(), createdAt, updatedAt: createdAt });
    if (!this.db.customTemplates) this.db.customTemplates = [];
    this.db.customTemplates.push(template);
    this.saveToStorage(this.db);
    return template;
  }

  getCustomTemplate(id: string): CustomTemplate | undefined {
    return (this.db.customTemplates || []).find((template) => template.id === id);
  }

  listCustomTemplates(): CustomTemplate[] {
    return [...(this.db.customTemplates || [])];
  }

  updateCustomTemplate(id: string, data: Partial<Omit<CustomTemplate, 'id' | 'createdAt'>>): CustomTemplate | undefined {
    const arr = this.db.customTemplates || [];
    const index = arr.findIndex((template) => template.id === id);
    if (index === -1) return undefined;
    const updated = normalizeCustomTemplate({ ...arr[index], ...data, id, updatedAt: nowIso() });
    arr[index] = updated;
    this.db.customTemplates = arr;
    this.saveToStorage(this.db);
    return updated;
  }

  deleteCustomTemplate(id: string): boolean {
    const arr = this.db.customTemplates || [];
    const index = arr.findIndex((template) => template.id === id);
    if (index === -1) return false;
    arr.splice(index, 1);
    this.db.customTemplates = arr;
    this.saveToStorage(this.db);
    return true;
  }

  // ─── Bills CRUD ──────────────────────────────────────────────

  createBill(data: Omit<Bill, 'id' | 'createdAt' | 'updatedAt'>): Bill {
    const createdAt = nowIso();
    const bill = normalizeBill({ ...data, id: uuid(), createdAt, updatedAt: createdAt });
    if (!this.db.bills) this.db.bills = [];
    this.db.bills.unshift(bill);
    this.saveToStorage(this.db);
    return bill;
  }

  getBill(id: string): Bill | undefined {
    return (this.db.bills || []).find((b) => b.id === id);
  }

  listBills(): Bill[] {
    return [...(this.db.bills || [])];
  }

  updateBill(id: string, data: Partial<Omit<Bill, 'id' | 'createdAt'>>): Bill | undefined {
    const arr = this.db.bills || [];
    const index = arr.findIndex((b) => b.id === id);
    if (index === -1) return undefined;
    const updated = normalizeBill({ ...arr[index], ...data, id, updatedAt: nowIso() });
    arr[index] = updated;
    this.db.bills = arr;
    this.saveToStorage(this.db);
    return updated;
  }

  deleteBill(id: string): boolean {
    const arr = this.db.bills || [];
    const index = arr.findIndex((b) => b.id === id);
    if (index === -1) return false;
    arr.splice(index, 1);
    this.db.bills = arr;
    this.saveToStorage(this.db);
    return true;
  }
}


export const db = new LocalStorageDB();
