import {
  AILocationCache,
  DepartmentProfile,
  DocumentVersion,
  Firm,
  LocalBodyType,
  PlaceMapping,
  Settings,
  Tender,
  TenderDocument,
  CustomTemplate,
  Bill,
} from '@/types';
import { defaultVersioningSettings } from '@/services/versioningSettings';

export interface Database {
  tenders: Tender[];
  firms: Firm[];
  documents: TenderDocument[];
  settings: Settings[];
  departmentProfiles: DepartmentProfile[];
  documentVersions: DocumentVersion[];
  purposeMappings: PurposeMapping[];
  itemHindiMappings: HindiMapping[];
  vendorHindiMappings: HindiMapping[];
  placeMappings: PlaceMapping[];
  localBodyTypes: LocalBodyType[];
  aiLocationCache: AILocationCache[];
  documentPhraseMappings: DocumentPhraseMapping[];
  customTemplates: CustomTemplate[];
  bills: Bill[];
}


export interface PurposeMapping {
  id: string;
  category: string;
  professionalPurpose: string;
  language: 'hindi' | 'english';
  usageCount: number;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

/**
 * Indexes for purposeMappings collection (for Firestore implementation):
 * - Compound index: (category, language) - for efficient lookups by category and language
 * - Single field index: createdAt - for sorting by creation date
 */

export interface HindiMapping {
  id: string;
  englishName: string;
  hindiName: string;
  englishDescription?: string;
  hindiDescription?: string;
  type: 'item' | 'vendor';
  usageCount: number;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

/**
 * Indexes for itemHindiMappings collection (for Firestore implementation):
 * - Compound index: (englishName, type) - for efficient lookups by English name and type
 * - Single field index: createdAt - for sorting by creation date
 */

/**
 * Indexes for vendorHindiMappings collection (for Firestore implementation):
 * - Compound index: (englishName, type) - for efficient lookups by English name and type
 * - Single field index: createdAt - for sorting by creation date
 * 
 * Firestore composite index configuration:
 * {
 *   "collectionGroup": "vendorHindiMappings",
 *   "queryScope": "COLLECTION",
 *   "fields": [
 *     { "field_path": "englishName", "order": "ASCENDING" },
 *     { "field_path": "type", "order": "ASCENDING" }
 *   ]
 * }
 * 
 * Firestore single-field index configuration:
 * {
 *   "collectionGroup": "vendorHindiMappings",
 *   "queryScope": "COLLECTION",
 *   "fields": [
 *     { "field_path": "createdAt", "order": "ASCENDING" }
 *   ]
 * }
 */

export interface DocumentPhraseMapping {
  id: string;
  categoryName: string;
  categoryId: string;
  keywords: string[];
  phrases: {
    supplyOrder: { subject: string };
    quotationMain: { english: string; hindi: string };
    quotation: { purchaseLine: string };
    quotationAltHindi: { subject: string };
    quotationAltEnglish: { subject: string };
    bill: { itemDescription: string };
  };
  generatedByAI: boolean;
  approved: boolean;
  usageCount: number;
  lastUsedAt?: string;
  englishDescription?: string;
  createdAt: string;
  updatedAt: string;
}

export const defaultDatabase: Database = {

  tenders: [],
  firms: [],
  documents: [],
  settings: [],
  departmentProfiles: [],
  documentVersions: [],
  purposeMappings: [],
  itemHindiMappings: [],
  vendorHindiMappings: [],
  placeMappings: [],
  localBodyTypes: [],
  aiLocationCache: [],
  documentPhraseMappings: [],
  customTemplates: [],
  bills: [],
};


export const defaultSettings: Settings = {
  id: 'default-settings',
  organizationName: 'Government Department',
  departmentAddress: '123 Government Road, City, State 12345',
  contactPerson: 'Department Head',
  email: 'contact@govt.in',
  phone: '+91-XXXXXXXXXX',
  defaultLanguage: 'english',
  headerSafeZonePx: 120,
  tenderNumberPrefix: 'TEND',
  enableLocationAIAutofill: false,
  versioningSettings: defaultVersioningSettings,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const sampleFirms: Firm[] = [
  {
    id: 'firm-1',
    name: 'ABC Supplies Ltd.',
    headerImagePath: '/letterheads/abc-letterhead.jpg',
    signatureImagePath: '/signatures/abc-signature.png',
    stampImagePath: '/stamps/abc-stamp.png',
    defaultLanguage: 'english',
    fitLetterheadMode: 'contain',
    headerSpacing: 170,
    footerSpacing: 120,
    pageMargin: 40,
    // Legacy fields (kept for older exports/imports).
    contentStartY: 170,
    pagePaddingLeft: 40,
    signatureOffsetX: 16,
    signatureOffsetY: 16,
    signatureScale: 1,
    signatureRotateDeg: 0,
    stampOffsetX: 140,
    stampOffsetY: 16,
    stampScale: 1,
    stampMode: 'image',
    aiPromptQuotation: 'Write concise government procurement quotation in formal English.',
    aiPromptBill: '',
    firmStyleProfile: 'govt_formal',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const sampleDepartmentProfile: DepartmentProfile = {
  id: 'dept-1',
  name: 'Municipal Corporation',
  address: '123 Government Road',
  city: 'New Delhi',
  state: 'Delhi',
  pincode: '110001',
  contactPerson: 'Department Head',
  email: 'municipal-corporation@govt.in',
  phone: '+91-11-XXXXX',
  headerStyle: 'govt',
  defaultLanguage: 'english',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const defaultLocalBodyTypes: LocalBodyType[] = [
  {
    id: 'local-body-nagar-palika-parishad',
    englishName: 'Nagar Palika Parishad',
    hindiName: 'नगर पालिका परिषद',
    usageCount: 0,
    isDefault: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'local-body-nagar-parishad',
    englishName: 'Nagar Parishad',
    hindiName: 'नगर परिषद',
    usageCount: 0,
    isDefault: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'local-body-nagar-palika',
    englishName: 'Nagar Palika',
    hindiName: 'नगर पालिका',
    usageCount: 0,
    isDefault: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const samplePlaceMappings: PlaceMapping[] = [
  {
    id: 'place-seondha',
    englishName: 'Seondha',
    hindiName: 'सेवढ़ा',
    districtName: 'Datia',
    districtHindiName: 'दतिया',
    stateName: 'Madhya Pradesh',
    stateHindiName: 'मध्य प्रदेश',
    localBodyType: 'Nagar Parishad',
    localBodyTypeHindi: 'नगर परिषद',
    usageCount: 0,
    isAutoGenerated: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'place-gwalior',
    englishName: 'Gwalior',
    hindiName: 'ग्वालियर',
    districtName: 'Gwalior',
    districtHindiName: 'ग्वालियर',
    stateName: 'Madhya Pradesh',
    stateHindiName: 'मध्य प्रदेश',
    localBodyType: 'Nagar Nigam',
    localBodyTypeHindi: 'नगर निगम',
    usageCount: 0,
    isAutoGenerated: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'place-datia',
    englishName: 'Datia',
    hindiName: 'दतिया',
    districtName: 'Datia',
    districtHindiName: 'दतिया',
    stateName: 'Madhya Pradesh',
    stateHindiName: 'मध्य प्रदेश',
    localBodyType: 'Nagar Palika',
    localBodyTypeHindi: 'नगर पालिका',
    usageCount: 0,
    isAutoGenerated: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
